site_name: Telegram Web App Authorization
site_url: https://swimmwatch.github.io/telegram-webapp-auth/
site_author: Dmitry Vasiliev
site_description: >-
  Python package that implements Telegram Web authentication algorithm.

repo_url: https://github.com/swimmwatch/telegram-webapp-auth
repo_name: swimmwatch/telegram-webapp-auth

copyright: Copyright &copy; 2023 - 2024 Dmitry Vasiliev

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: deep blue
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: blue
      accent: deep blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/swimmwatch/telegram-webapp-auth/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/telegram-webapp-auth/

nav:
  - Home: index.md
  - Guide:
      - Installation: guide/install.md
      - Examples:
          - Django: guide/examples/django.md
          - FastAPI: guide/examples/fastapi.md
  - References:
      - Authorization: references/auth.md
      - Data: references/data.md
      - Errors: references/errors.md
  - License: license.md

plugins:
  - search
  - section-index
  - coverage
  - mkdocstrings:
      default_handler: python
  - macros:
      include_dir: .
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
