name: "Web changes detector"
author: swimmwatch
description: "Detect changes in web pages and notify via GitHub Actions"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  config:
    description: "Configuration for the web changes detector"
    required: true
  jobs:
    description: "List of jobs to run for web changes detection"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Write configs to files"
      shell: bash
      run: |
        echo "${{ inputs.config }}" > config.yaml
        echo "${{ inputs.jobs }}" > jobs.yaml
    - name: "Setup Python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: "pip"
    - name: "Install webchanges"
      shell: bash
      run: |
        pip install webchanges
    - name: "Run web changes detection"
      shell: bash
      run: |
        webchanges --config config.yaml --jobs jobs.yaml --hooks ${{ github.action_path }}/hooks.py
