name: "Web changes detector"
author: swimmwatch
description: "Detect changes in web pages and notify via GitHub Actions"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  config:
    description: "Configuration for the web changes detector"
    required: true
  jobs:
    description: "List of jobs to run for web changes detection"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Write configs to files"
      shell: bash
      run: |
        echo "${{ inputs.config }}" > config.yaml
        echo "${{ inputs.jobs }}" > jobs.yaml
    - name: "Compute SHA-256 of configs input"
      shell: bash
      run: |
        # Compute the hash of the config input and store it in an environment variable
        echo "${{ inputs.config }}" | sha256sum | awk '{ print $1 }' > config_hash.txt
        HASH=$(cat config_hash.txt)
        echo "CONFIG_HASH=$HASH" >> $GITHUB_ENV
        
        # Compute the hash of the jobs input and store it in an environment variable
        echo "${{ inputs.jobs }}" | sha256sum | awk '{ print $1 }' > jobs_hash.txt
        HASH=$(cat jobs_hash.txt)
        echo "JOBS_HASH=$HASH" >> $GITHUB_ENV
    - name: "Setup Python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: "pip"
    - name: "Install webchanges"
      shell: bash
      run: |
        pip install webchanges
    - name: "Restore cache snapshots database"
      id: cache-db
      uses: actions/cache@v4
      with:
        path: ./snapshots.db
        key: ${{ runner.os }}-snapshots-${{ env.CONFIG_HASH }}-${{ env.JOBS_HASH }}
        restore-keys: |
          ${{ runner.os }}-snapshots-${{ env.CONFIG_HASH }}-${{ env.JOBS_HASH }}
    - name: "Check if snapshots database exists"
      shell: bash
      run: |
        if [ ! -f snapshots.db ]; then
          echo "No snapshots database found, creating a new one."
        else
          echo "Snapshots database found, using existing one."
        fi
    - name: "Run web changes detection"
      shell: bash
      run: |
        webchanges --config config.yaml --jobs jobs.yaml --hooks ${{ github.action_path }}/hooks.py --database snapshots.db
